#!/bin/bash

set -ieu

source ../harmony/scripts/setup_bls_build_flags.sh

sender='one1yc06ghr2p8xnl2380kpfayweguuhxdtupkhqzw'
receiver='one1q6gkzcap0uruuu8r6sldxuu47pd4ww9w9t7tg6'
shard_zero='https://api.s0.b.hmny.io/'
shard_one='https://api.s0.b.hmny.io/'

direct_node='http://52.27.34.100:9500'

function c {
    printf "%s\n" "$*" | bc
}

# Shard 0 to 0
for iter in $(seq 100); do
    rand=$(grep -m1 -ao '[0-9]' /dev/urandom | sed s/0/3/ | head -n1)
    value=$(c "${iter}/100")
    bump=$(c "${value}+${rand}")
    amount=$(printf "%.2f" ${bump})
    ./hmy --node=${shard_zero} \
	  transfer --from ${sender} --to ${receiver} \
	  --from-shard 0 --to-shard 0 --amount ${amount} \
	  --passphrase='' &
done
